spring:
  datasource:
    url: jdbc:mysql://localhost:3306/root?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: kerabi0424
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
